import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :next_gear_motors, NextGearMotorsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Configures mail
config :next_gear_motors, NextGearMotors.Mailer,
  adapter: Swoosh.Adapters.Mua,
  relay: {:system, "SMTP_RELAY"},
  auth: [
    username: {:system, "SMTP_USERNAME"},
    password: {:system, "SMTP_PASSWORD"}
  ],
  port: 587

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: NextGearMotors.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :waffle,
  storage: Waffle.Storage.S3,
  bucket: {:system, "BUCKET_NAME"},
  asset_host: {:system, "AWS_ENDPOINT_URL_S3"}

config :ex_aws,
  debug_requests: true,
  access_key_id: {:system, "AWS_ACCESS_KEY_ID"},
  secret_access_key: {:system, "AWS_SECRET_ACCESS_KEY"}

config :ex_aws, :s3,
  scheme: "https://",
  host: "fly.storage.tigris.dev",
  region: "auto"
